### ISSUE TITLE
Incorrect equation for rotor dynamics

### ISSUE THREAD

**Issue by TZ2016** [ethz-asl/rotors_simulator#256]
In file gazebo_motor_model.cpp, method UpdateForcesAndMoments():
the following line calculate the perpendicular component of body velocity:
  math::Vector3 body_velocity_perpendicular = body_velocity - (body_velocity * joint_axis) * joint_axis;

According to the reference documentation, the first asterisk is meant to be a dot product.
However, according to Gazebo documentation on math::Vector3, operator* is element-wise multiplication. For dot product, should instead use vector.Dot(another_vector).

**Comment by markusachtelik** [comment]
fixed in #257
