### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by sytelus** [ethz-asl/rotors_simulator#306]
It looks like attitude_control.h is referencing below two files:

```
#include "rotors_control/controller_base.h"
#include "rotors_control/controller_factory.h"
```

However I can't find these two headers anywhere in repo. Are they missing? Is this branch still compilable?

**Comment by pvechersky** [comment]
@sytelus,

The two header files you're referring to used to be part of the 'rotors_control' package but were removed in pull request #177 ... So I think those includes should be removed, but in the meantime the branch should still compile.

**Comment by sytelus** [comment]
Thanks! I'm wondering if attitude controller is working or tested. If its still in works, I would avoid using it for now.

**Comment by pvechersky** [comment]
@sytelus 

My bad, I just now saw that the attitude controller files do not actually get compiled. I haven't really dealt with the controller side of RotorS before. I think @burrimi would know a lot more about the state of the attitude controller.

**Comment by burrimi** [comment]
Hi sytelus,
this is a leftover of our old controller factory implementation, which allowed to switch controllers easily but added quite a lot of complexity. We droped it because we wanted to make the code for rotors as simple as possible. In the process of removing the factory we forgot to delete these files. But they are never compiled or included in the cmake project and should not lead to any problems.

**Comment by AbhinayNS** [comment]
hi, 
i was actually trying to model the attitude control loop as a second order system and for that i wanted to give roll and pitch commands for the x and y axis control and position input for the z axis control. 
From what i have observed, none of the controller nodes are capable of doing this, so i wanted to create a attitude control node but again I faced the same issue of the those two header files not being available. Could anyone suggest me something on how do I go about this and is there already a way where in we can give roll and pitch commands for x and y axes and position or velocity command for the z axis.
