### ISSUE TITLE
No "real" hovering?

### ISSUE THREAD

**Issue by sytelus** [ethz-asl/rotors_simulator#307]
It appears that most examples in launch folder uses lee controller with ground truth odometry. I want to just use IMU and demonstrate that quadrotor drifts in simulation. For this we need modules for pose estimation and PID controller. Are these available for RotorS? The paper mentions that it used "Orocos" toolchain which is supposed to do this. I'm wondering if that or any other code is available to use with RotorS simulator to basic simulation of drifting quadrotor.

Thanks.

**Comment by Jaeyoung-Lim** [comment]
@sytelus You can try running a software-in-the-loop simulation using PX4, and configure the EKF to only use IMU sensors. Further information can be found in: http://docs.px4.io/master/en/simulation/
