### ISSUE TITLE
Any updates about the fixed-wing control?

### ISSUE THREAD

**Issue by weiweikong** [ethz-asl/rotors_simulator#310]
Is there any guidance related to the fixed-wing command topic?
Just launch the fixed-wing model in gazebo, using`fixed_wing.launch`,  however, there is no command topic for ros.

**Comment by pvechersky** [comment]
@weiweikong 

I am currently working on integrating more code for fixed-wing flight, I will give you more information soon :)

**Comment by weiweikong** [comment]
@pvechersky Great! Just tested some of the fixed_wing_sim in your branch and meet some problems. Some detail has been sent to your e-mail. I am glad to contribute some testing and edit some basic guidance about it. :)
