### ISSUE TITLE
how to control the rotors using joystick?

### ISSUE THREAD

**Issue by jazsonma** [ethz-asl/rotors_simulator#314]
I try to use the joy_interface launch file and the joystick. however,it doesn't work.

**Comment by pvechersky** [comment]
@jazsonma 

Earlier this week I started using a joystick to fly a MAV in RotorS and it worked fine for me.

- Are you using the 'mav_with_joy.launch' file?
- Do you get any error messages in your console when you run the launch file? (like device not found or missing files)
- Keep in mind that our launch files start Gazebo in paused mode. Make sure you un-pause the simulation or change the 'paused' flag to false in order for the MAV to fly.

**Comment by jazsonma** [comment]
@pvechersky 
yes,when i change the 'paused' flag to false in the 'mav_with_joy.launch' file ,it can  fly.Thanks!

**Comment by jazsonma** [comment]
@pvechersky 
yes, when I change the 'paused' flag to false ,it can fly

**Comment by ffurrer** [comment]
Closing, as this seems to be resolved.
