### ISSUE TITLE
"Undefined symbol" linking error when adding GazeboRosInterfacePlugin calls to the GazeboMultirotorBase class. 

### ISSUE THREAD

**Issue by gbmhunter** [ethz-asl/rotors_simulator#330]
Error:

````
[Err] [Plugin.hh:165] Failed to load plugin librotors_gazebo_multirotor_base_plugin.so:
/home/gbmhunter/catkin_ws/devel/lib/librotors_gazebo_multirotor_base_plugin.so:
undefined symbol: _ZN6gazebo24GazeboRosInterfacePlugin8instanceE
````

**Comment by gbmhunter** [comment]
Fixed.

**Comment by Matnay** [comment]
Could you please let me know how you fixed this. I am having a similar issue and have not been able to find a workaround yet.
```
gzserver: symbol lookup error: /home/matnay/rotors_ws/devel/lib/librotors_gazebo_multirotor_base_plugin.so: undefined <br>symbol: _ZN14gz_sensor_msgs9ActuatorsC1Ev
```

**Comment by guiaugustoga** [comment]
Ha

> Could you please let me know how you fixed this. I am having a similar issue and have not been able to find a workaround yet.
> 
> ```
> gzserver: symbol lookup error: /home/matnay/rotors_ws/devel/lib/librotors_gazebo_multirotor_base_plugin.so: undefined symbol: _ZN14gz_sensor_msgs9ActuatorsC1Ev
> ```
> 
> Thank you

Having the same issue. Any news ?
