### ISSUE TITLE
Random walk noise typo?

### ISSUE THREAD

**Issue by jgoppert** [ethz-asl/rotors_simulator#335]
This is a repost of https://github.com/PX4/sitl_gazebo/pull/73 but the code is the same in both repos.

I believe there is a typo, you can confirm by comparing to Maybeck (vol. 1 pg 173)

```
Maybeck: Qd = Q*/(2T) * [ 1 - e^(-2dt/T)]
Our equation: Qd = QT/2 * [ 1 - e^(-2*dt/T)]
```

I discovered this through Allan Variance plots and the original plots were highly impacted by random walk. We were effectively multiplying the random walk standard deviation by the correlation time constant (300).

You can see plots of the comparison here from running each for 10 minutes:

https://github.com/jgoppert/iekf_analysis/blob/master/Noise%20Fix.ipynb

patch:

https://github.com/PX4/sitl_gazebo/pull/73/commits/643d42cf436265abbdeda2917834f59c99768b42

**Comment by burrimi** [comment]
see https://github.com/PX4/sitl_gazebo/pull/73
