### ISSUE TITLE
How to use this package with mavros support? (control MAV by mavros topic)

### ISSUE THREAD

**Issue by BossKwei** [ethz-asl/rotors_simulator#349]
Current package can not work correctly in ubuntu16.04 with ros kinetic

```
hil_state_level_interface.cpp:17:0:
hil_interface.h:106:3:
error: ‘mavlink_hil_gps_t’ does not name a type mavlink_hil_gps_t hil_gps_msg_;
```

**Comment by ckchow** [comment]
I'm not sure how to use this with mavros (or if it's possible), but you can get it to build on 16.04 + kinetic by blacklisting the rotors_hil_interface plugin. I.e. `touch rotors_hil_interface/CATKIN_IGNORE`.

**Comment by BossKwei** [comment]
Thanks
