### ISSUE TITLE
Problem with rotors yaw control

### ISSUE THREAD

**Issue by YuChingMai** [ethz-asl/rotors_simulator#359]
Hi all, 
I have a problem with joystick in yaw control doesn't work,
pitch and roll function is working fine, 
does any one have same problem?

**Comment by YuChingMai** [comment]
oh!! I found solution!!
thanks!!

**Comment by hitimo** [comment]
@YuChingMai For the case that somebody else has the same problem: what was the solution? :)

**Comment by giorgiovaccarino** [comment]
Hi, I have the same problem with joystick and I am not able to resolve despite many tries to mapping axes and button on the joystick.
Roll, pitch and throttle works!

**Comment by giorgiovaccarino** [comment]
I found the problem, since the yaw is controlled by a button you cannot see  anything until you press many many times that button.
