### ISSUE TITLE
CAN the ROTOR S Be installed in Ubuntu 16.04 and ROS Kinetic?

### ISSUE THREAD

**Issue by shravank1996** [ethz-asl/rotors_simulator#362]
I tried installing Rotor S in Kinect but the system states the following:
ssh: connect to host github.com port 22: No route to host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

How Do I solve the problem?
![rotors error](https://cloud.githubusercontent.com/assets/26010396/24072479/73823d70-0c0d-11e7-9854-aaa7c742eb7c.png)

**Comment by vanurag** [comment]
@shravank1996 You are cloning with SSH option which requires you to have SSH keys. Try https version. so simply: git clone https://github.com/ethz-asl/rotors_simulator.git

**Comment by shravank1996** [comment]
What about the other keys?

**Comment by pvechersky** [comment]
@shravank1996 To fix this for the other repos, you can:

1) Set up the SSH connection to your github account (https://help.github.com/articles/connecting-to-github-with-ssh/). This way, you won't have to worry about this going forward.

OR

2) For each repo you want to clone, find it on Github with a search, click on 'Clone or download', make sure it says 'Clone with HTTPS' and copy the link it provides.

OR

3) For each repo listed in step 3 of installation instruction, just generate the HTTPS link yourself: replace "git@" with "https://" and the colon with a forward slash.

**Comment by shravank1996** [comment]
Thanks or the help ,OK I am now getting a new error
Source space `/home/shravan/src` does
not yet exist.
 How do i rectify it?

**Comment by shravank1996** [comment]
actually it exists in a different directory actually in windows folder

**Comment by shravank1996** [comment]
Hey I got the system to work The Catkin Folder was not created Properly but then this error popped up when I try to run the system
Any help?
![rotors intialisation error](https://cloud.githubusercontent.com/assets/26010396/24081909/9d994484-0ce2-11e7-9232-377ebefcb896.png)

**Comment by pvechersky** [comment]
- When you say that the catkin folder was not created properly what do you mean by that?
- Did the workspace build successfully?
- If the build did complete fine, it looks like ROS can't find your packages. Are you sourcing the .../devel/setup.bash file in your workspace?

**Comment by shravank1996** [comment]
The Devel folder was not created Hence the system couldnt create Bash.setup.
Then when I reintialised catkin the workspace did build cause Bash did get set.
I did source it

**Comment by shravank1996** [comment]
I think it was intialised properly and I did source the devel/setup.bash file into my workspace but now the system is showing a new error.
Can anyone please help me
![gazebo](https://cloud.githubusercontent.com/assets/26010396/24446414/f6464f28-148a-11e7-9b6d-028d59b9fa55.jpeg)

**Comment by shravank1996** [comment]
![brolen package](https://cloud.githubusercontent.com/assets/26010396/24452520/4cf7f432-14a1-11e7-812b-33a6470f4e58.png)
Terminal says Broken Gazebo Package
Is it a problem caused by me having gazebo installed before installing ROS?
Please help

**Comment by robrother** [comment]
Hi, my name is Erick, I'm trying to install RotorS and I was following the steps to install using Kinetic, but I have an error when I write _wstool merge rotors_hill.rosinstall_, could anybody help me to resolve this?
![error rotors](https://user-images.githubusercontent.com/31225988/32136697-d2fc6030-bbd7-11e7-9a73-7b71ff4a9de5.JPG)

**Comment by ffurrer** [comment]
Please open new issues if you have specific questions, will close this one.
