### ISSUE TITLE
scalar of /firefly/ground_truth/transform quaternion stays 0

### ISSUE THREAD

**Issue by hitimo** [ethz-asl/rotors_simulator#371]
- [x] Find out why scalar of /firefly/ground_truth/transform quaternion stays 0 for all times
`/firefly/ground_truth/transform` vs `/firefly/ground_truth/imu`
![rotors_ground_truth](https://cloud.githubusercontent.com/assets/5558652/24135072/575e49a2-0e08-11e7-9d41-f66370de035f.png)

**Comment by burrimi** [comment]
fixed in https://github.com/ethz-asl/rotors_simulator/pull/372
