### ISSUE TITLE
(question) moving to a real vehicle

### ISSUE THREAD

**Issue by andre-nguyen** [ethz-asl/rotors_simulator#375]
In the book there is mention of how the simulation is accurate enough to reuse the same controllers on a real vehicle except for the fact that you use roll pitch yaw and trust commands instead of direct motor commands. Suppose I wanted to use the Lee position controller on a Firefly, how would I go about doing this?

**Comment by burrimi** [comment]
In our lab we use these publicly available position/trajectory tracking controllers: https://github.com/ethz-asl/mav_control_rw
@fmina wrote a nice bookchapter how to use these and they should already include the tuning parameters for the firefly.

**Comment by andre-nguyen** [comment]
Ah that answers it.
