### ISSUE TITLE
Package versioning is wrong

### ISSUE THREAD

**Issue by fmina** [ethz-asl/rotors_simulator#393]
Please when you add a new package use the correct RotorS release version. 
https://github.com/ethz-asl/rotors_simulator/blob/master/rqt_rotors/package.xml#L3 
Otherwise releasing will fail.
Check out this. http://answers.ros.org/question/60138/bloom-runtimeerror-two-packages-have-different-version-numbers/

**Comment by ffurrer** [comment]
Can we close this? I added this to the wiki: https://github.com/ethz-asl/rotors_simulator/wiki/Package-Versioning.
