### ISSUE TITLE
Tricopter with tiltrotor - gazebo_multirotors_base_plugin

### ISSUE THREAD

**Issue by ganeshrk95** [ethz-asl/rotors_simulator#400]
Hey guys!

I'm working on Tricopter with a tilt servo operating the back motor. I have not seen any model with actuated links in series. In my model, the parent-chile tree is as follows:

->base_link
----->Front_right
----->Front_left
----->TILT_servo
----------->Back_motor

All the reference models/examples provided have a single base_link (parent) and rotors as child links. In my case the TILT_servo is the parent for Back_motor. Can someone guide how to go about this ?

Thanks in advance.

-Ganesh

**Comment by ganeshrk95** [comment]
I am using the PX4 stack. When I command the servo link to take some position, I cannot get the back motor to rotate which is on another channel. I have setup the mavlink_controller in the following manner:
Ch1: Front Right Motor
Ch2: Front Left Motor
Ch3: Back Motor
Ch4: Servo Motor

I can give only one. either Ch3 or Ch4. I think the problem arises because BACK MOTOR's parent link is the SERVO MOTOR and the SERVO MOTORs' parent is the BASE_LINK.

**Comment by ganeshrk95** [comment]
If you can guide me regarding the part of the code which needs to be modified, that would be of great help.

**Comment by ghostold** [comment]
did U get it worked？could U please share the way to setup the back servo？

**Comment by suraj2596** [comment]
@ganeshrk95 , could you elaborate on your project little more?

**Comment by Jaeyoung-Lim** [comment]
Closing stale
