### ISSUE TITLE
How to import two hummingbird uavs in one scene?

### ISSUE THREAD

**Issue by jiaweimeng** [ethz-asl/rotors_simulator#401]
Hi guys,

Recently I am using gazebo and working on uavs simulation. What I plan to do is use multi-uavs to do some cool path planning. However, the issue now is that I cannot import 2 hummingbird uavs in one scene and the error shows that the model name "hummingbird" has already exist. Can anyone help me with this problem please?  Thank you very much:)

**Comment by jiaweimeng** [comment]
<group ns="hummingbird">
    <include file="$(find rotors_gazebo)/launch/spawn_mav.launch">
      <arg name="mav_name" value="hummingbird" />
      <arg name="model" value="$(find rotors_description)/urdf/mav_generic_odometry_sensor.gazebo" />
      <arg name="enable_logging" value="$(arg enable_logging)" />
      <arg name="enable_ground_truth" value="$(arg enable_ground_truth)" />
      <arg name="log_file" value="hummingbird"/>
      <arg name="y" value="0.0"/>
    </include>
    <node name="lee_position_controller_node" pkg="rotors_control" type="lee_position_controller_node" output="screen">
      <rosparam command="load" file="$(find rotors_gazebo)/resource/lee_controller_hummingbird.yaml" />
      <rosparam command="load" file="$(find rotors_gazebo)/resource/hummingbird.yaml" />
      <remap from="odometry" to="odometry_sensor1/odometry" />
    </node>
    <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />
    <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" />
    <node name="waypoint_publisher_file" pkg="rotors_gazebo" type="waypoint_publisher_file" output="screen" args="$(find rotors_gazebo)/resource/example_waypoints2.txt"/>
  </group>

  <group ns="hummingbird_1">
    <include file="$(find rotors_gazebo)/launch/spawn_mav.launch">
      <arg name="mav_name" value="hummingbird" />
      <arg name="model" value="$(find rotors_description)/urdf/mav_generic_odometry_sensor.gazebo" />
      <arg name="enable_logging" value="$(arg enable_logging)" />
      <arg name="enable_ground_truth" value="$(arg enable_ground_truth)" />
      <arg name="log_file" value="hummingbird"/>
      <arg name="y" value="1.0"/>
    </include>
    <node name="lee_position_controller_node" pkg="rotors_control" type="lee_position_controller_node" output="screen">
      <rosparam command="load" file="$(find rotors_gazebo)/resource/lee_controller_hummingbird.yaml" />
      <rosparam command="load" file="$(find rotors_gazebo)/resource/hummingbird.yaml" />
      <remap from="odometry" to="odometry_sensor1/odometry" />
    </node>
    <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />
    <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" />
    <node name="waypoint_publisher_file" pkg="rotors_gazebo" type="waypoint_publisher_file" output="screen" args="$(find rotors_gazebo)/resource/example_waypoints1.txt"/>
  </group>

**Comment by marco-tranzatto** [comment]
Check how groups and namespaces (documentation [here](http://wiki.ros.org/roslaunch/XML/group) ) are used in this launch file: [https://github.com/ethz-asl/rotors_simulator/blob/master/rotors_gazebo/launch/firefly_swarm_hovering_example.launch](https://github.com/ethz-asl/rotors_simulator/blob/master/rotors_gazebo/launch/firefly_swarm_hovering_example.launch)

;)

**Comment by ffurrer** [comment]
@jiaweimeng if the above suggestion worked for you, can you close this?
