### ISSUE TITLE
Fixed Wing HIL Simulation not working

### ISSUE THREAD

**Issue by acfloria** [ethz-asl/rotors_simulator#402]
The GPS, pressure, and IMU plugin use the Gazebo transport system. The outdated HIL interface still uses ROS. Therefore, it does not receive any sensor message.

I work on solving this issue.

**Comment by pvechersky** [comment]
@acfloria The 'ros_interface_plugin' (to be included in the world file) is designed to convert the gazebo transport messages to ROS. So I think that HIL interface should work with that, assuming the topic names are consistent ...

**Comment by acfloria** [comment]
@pvechersky I did not know that, thanks pointing that out. I will test it.

**Comment by hitimo** [comment]
@acfloria Okay to close?
