### ISSUE TITLE
The process of catkin build won't succeed problem building the gazebo_plugins 

### ISSUE THREAD

**Issue by ZakariaChekakta** [ethz-asl/rotors_simulator#415]
Hi, I am trying to build the rotors_simulator, specifically  building the gazebo_plugins 

![erreur findglog](https://user-images.githubusercontent.com/12950797/27454064-dff653fc-5798-11e7-917b-8aff3bfe09bc.png)

**Comment by shelderzhang** [comment]
```
sudo apt-get update
sudo apt-get install libgoogle-glog-dev
catkin clean
catkin build
```
