### ISSUE TITLE
Incomplete installation instruction

### ISSUE THREAD

**Issue by m-janicki** [ethz-asl/rotors_simulator#431]
Installation instruction in README.md are incomplete. I have faced following issues.

1. Missing octomap libraries
Fix:
```
sudo apt install ros-kinetic-octomap ros-kinetic-octomap-mapping
rosdep install octomap_mapping
rosmake octomap_mapping
```

2. Missing glog library
Fix:
```
sudo apt install libgoogle-glog-dev
```

3. Missing protobuf compiler
Fix:
```
sudo apt install protobuf-compiler
```

4. Instruction says to download repo via ssh, https link would be better, because it doesn't need rsa key.

I don't know if my fixes are the best solution of solving these issues.

**Comment by ffurrer** [comment]
@m-janicki I added the glog-dev system dependency, even though we usually got this from https://github.com/ethz-asl/glog_catkin, all the other required packages were already in the instructions, as far as I know. But thanks for posting your solution.
