### ISSUE TITLE
unable to fly the fixed_wing in gazebo

### ISSUE THREAD

**Issue by amrii1** [ethz-asl/rotors_simulator#446]
i started the fixed_wing_with_joy.launch file along with the rc virtual joy node in the gazebo simulator but the plane didn't fly. should i call fixed wing configuration in the launch file ? any suggestions ? how can i make it fly? thanks .

**Comment by hitimo** [comment]
Are the control surfaces moving? Which world did you use? I successf. tested with [rafz.world](https://github.com/pvechersky/rotors_simulator/blob/feature/fixed_wing_sim/rotors_gazebo/worlds/rafz.world).

**Comment by Jaeyoung-Lim** [comment]
Closing as stale
