### ISSUE TITLE
Problem installing RotorS on Distro Kinetic

### ISSUE THREAD

**Issue by robrother** [ethz-asl/rotors_simulator#451]
Hello 

My name is Erick, I´m new using ROS and I´m trying to install RotorS Simulator, mi distro is Kinetic, and when in my workspace I write catkin_make the system says that the package does not folllow version conventions.
 
![image](https://user-images.githubusercontent.com/31225988/32996394-b0a141dc-cd47-11e7-8710-4b0ea464dd10.png)

Could anybody help me saying me what I need change? 

Greetings from México

Erick

**Comment by helenol** [comment]
Try `catkin build rotors_simulator` instead :)

**Comment by robrother** [comment]
Hi @helenol , thanks for your soon answer, unfortunately I have the same problem with the version package
![image](https://user-images.githubusercontent.com/31225988/33030762-c5418396-cde1-11e7-9cb3-cd680528a519.png)
I think that I need change something here, in the version package, but I don't know the correct convention.
![image](https://user-images.githubusercontent.com/31225988/33030935-4742ecfe-cde2-11e7-98cf-fc18552aa337.png)

**Comment by helenol** [comment]
```
cd ~/catkin_ws/
catkin clean --all
catkin build rotors_simulator
```

Alternatively just delete `~/catkin_ws/build` (the build folder that the first message refers to), but if `catkin clean --all` works this is a nicer option.

**Comment by robrother** [comment]
Hi @helenol thanks for your help, finally I could install it, I have to create a new workspace and I do all the steps again.
![image](https://user-images.githubusercontent.com/31225988/33104864-fd6ce33c-ceef-11e7-88e7-f1c74a353679.png)
