### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by xinhaixufan** [ethz-asl/rotors_simulator#459]
I am on Ubuntu16.04 ROS Kinetic. When I run `catkin build `, I got these errors, Thanks!
![image](https://user-images.githubusercontent.com/20500881/34703243-ea3f9c92-f52c-11e7-9242-6da1d9e0e3f5.png)
![image](https://user-images.githubusercontent.com/20500881/34703253-fa028b3a-f52c-11e7-822e-f9a0ef44d9ec.png)
![image](https://user-images.githubusercontent.com/20500881/34703267-07d53d98-f52d-11e7-8483-fcf833275a82.png)

**Comment by ffurrer** [comment]
you need to install octomap_msgs:
```
sudo apt-get install ros-<version>-octomap-msgs
```
or just
```
sudo apt-get install ros-<version>-octomap
```
[octomap_msgs](https://github.com/OctoMap/octomap_msgs)
[octomap](http://wiki.ros.org/octomap)

please close this if it solved your issue

**Comment by xinhaixufan** [comment]
Thank you very much, It worked
