### ISSUE TITLE
Hovering_example launch error

### ISSUE THREAD

**Issue by xinhaixufan** [ethz-asl/rotors_simulator#462]
When i run this command: roslaunch rotors_gazebo mav_hovering_example.launch mav_name:=firefly world_name:=basic, there is an error occured. 

ERROR: cannot launch node of type [rotors_gazebo/hovering_example]: can't locate node [hovering_example] in package [rotors_gazebo]

Ubuntu16.04 and ROS kinetic

Thanks!

**Comment by m-erdem** [comment]
I was having the same error. I reinstalled all packages and use "catkin build" command instead of "catkin_make" to build workspace. Do you use  "catkin build" and get the same error ?

**Comment by aka-LJ** [comment]
I am on Ubuntu16.04 + Kinetic,
i used catkin build, didn't get the error.
