### ISSUE TITLE
Quadrotor is dropping after some time 

### ISSUE THREAD

**Issue by indsy123** [ethz-asl/rotors_simulator#463]
Hi, 
I reinstalled rotors_simulator with ubuntu 16.04 and ROS kinetic.  I implemented Lee's velocity controller using a python code and was trying to use this simulator when I observed that the quadrotor falls off after some time. Interestingly some time back (on a ubuntu 14.04 machine) my implementation of position and attitude controller were working fine. I kept debugging my code for errors but now notice similar behavior (quad goes to hover point but then drops after some time) with the default controller of this package. 

I can see the publishing rate of odometry sensor is 10 Hz but if I remember correctly it was 100hz before. I get few warning related to FindEigen.cmake is deprecated. And I cant install hil-plugin. Is there a problem with the installation or dependencies or controller+gazebo physics? I noticed same issue on 3 machines and cant figure out the reason. 

I would really appreciate any help regarding this.

**Comment by aeudes** [comment]
I observe the same behaviour. It is not normal that the odometry drop to 10Hz, it should be at least 100Hz for correct behaviour of rpy controller. 
The last commit introduce in #457 make this regression and revert it correct the problem.

The frequency of the odometry plugin depends on the update loop rate of gazebo and it is set differently in each world : real_time_update_rate=100/500/1000 and max_step_size=0.01 or 0.002.
