### ISSUE TITLE
catkin build;errors rotors_hil_interface:make;mavlink_hil_gps_t

### ISSUE THREAD

**Issue by 1184** [ethz-asl/rotors_simulator#470]
Hi,

I am on Ubuntu 16.04 with ROS Kinetic, I got the error message after the catkin build .Would you help me?Thank for your time!

error: ‘mavlink_hil_gps_t’ does not name a type
   mavlink_hil_gps_t hil_gps_msg_;
![2018-03-05 17-13-24](https://user-images.githubusercontent.com/37065656/36969335-2a468622-20a0-11e8-8a62-8f34f19531c8.png)
![2018-03-05 17-13-56](https://user-images.githubusercontent.com/37065656/36969337-2a976c7c-20a0-11e8-97bd-cb956ade6966.png)
![2018-03-05 17-14-30](https://user-images.githubusercontent.com/37065656/36969339-2ae311d6-20a0-11e8-84db-4dbb2c7f696e.png)
![2018-03-05 17-14-51](https://user-images.githubusercontent.com/37065656/36969342-2b816bf6-20a0-11e8-96a0-adbbcd3f45a2.png)

**Comment by dannyjose** [comment]
I had ptoblems too, try 
"pip install future " before "catkin buil"

**Comment by 1184** [comment]
It woks.Thank you so much.

**Comment by HusseinHazem** [comment]
i tried it but rotors_hil_interface still won't build
![newerror](https://user-images.githubusercontent.com/36478570/39362657-87ae8a02-4a27-11e8-8a15-b8adb1397d47.png)

**Comment by v01d** [comment]
@dannyjose Why should that fix this problem?
@HusseinHazem how did you manage to solve the original build error?

**Comment by Pedro-Roque** [comment]
This will fix it:
https://github.com/ethz-asl/rotors_simulator/pull/522/files?fbclid=IwAR2SxViGule-u8S4A1kE0L6HCwW3cixtO7IgMBNTp9TILT62TGdXPlsxApw

Big thumbs up for @TSC21 !

**Comment by EdXian** [comment]
Hi @Pedro-Roque ,
I used the ros-melodic version and I tried to build rotors_simulation. I got the same error which @1184  had described. I followed the step to fix the problem. However, I got a new error as the follows:
![image](https://user-images.githubusercontent.com/28064159/51127848-7d9f5880-1861-11e9-8663-71c339a2156f.png)
Can you give me some suggestions?
Thank you

**Comment by Pedro-Roque** [comment]
I'm not sure if Melodic is supported. However, it seems that a library is missing and so the namespace math is not being recognized.

**Comment by Pedro-Roque** [comment]
@EdXian please read
https://github.com/ethz-asl/rotors_simulator/blob/master/rotors_gazebo/launch/firefly_swarm_hovering_example.launch

and other RotorS doc
