### ISSUE TITLE
Can not launch node: lee_position_controller_node

### ISSUE THREAD

**Issue by xinhaixufan** [ethz-asl/rotors_simulator#478]
After it built successfully and ran this command: roslaunch rotors_gazebo mav_hovering_example.launch mav_name:=firefly world_name:=basic
some problems occurred, just like following:
![2018-04-06 20-50-29](https://user-images.githubusercontent.com/20500881/38422118-28f37afa-39dc-11e8-8d51-99855f08bdd7.png)

What should I do to resolve this problem?
Thank you!

**Comment by ffurrer** [comment]
Did you source the `setup.bash` after the `catkin build` command?
```
source ~/catkin_ws/devel/setup.bash
```
If your catkin workspace is somewhere else you need to adapt the path in the command above.

If this doesn't work, can you report the output of (you can add the `-v` flags to the commands below to get more output and and `--no-deps` to only build the specific package):

```
catkin build rotors_control
```
and
```
catkin build rotors_gazebo
```
