### ISSUE TITLE
 IMU plugin

### ISSUE THREAD

**Issue by tongtybj** [ethz-asl/rotors_simulator#486]
I am considering to use imu plugin in gazebo.
What is the main difference between  imu plugin in your repository and [GazeboRosImuSensor](http://gazebosim.org/tutorials?tut=ros_gzplugins)?

**Comment by ffurrer** [comment]
We have a bit an extended noise model. We created this, as we had some issues with the measurements on the default IMU plugin, you mentioned above, back when we wrote the simulator.

You can compare them:
https://github.com/ethz-asl/rotors_simulator/blob/master/rotors_gazebo_plugins/src/gazebo_imu_plugin.cpp

and:
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/src/gazebo_ros_imu_sensor.cpp
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/src/gazebo_ros_imu.cpp
https://bitbucket.org/osrf/gazebo/src/8234fc47cfbd800514cbd003a408ded5f713de29/gazebo/sensors/ImuSensor.cc?at=default&fileviewer=file-view-default
