### ISSUE TITLE
Additional packages required for succesful build

### ISSUE THREAD

**Issue by nkhedekar** [ethz-asl/rotors_simulator#492]
There are a few additional packages that are required to be installed for a successful build that have not been mentioned in the installation. In case RotorS does not get built even after installing these, calling `catkin clean` and then rebuilding solves the problem.

These packages can be installed using the following commands -
`
sudo -H pip install future 
`
`
sudo apt-get install ros-kinetic-octomap-msgs ros-kinetic-octomap-mapping libgoogle-glog-dev ros-kinetic-control-toolbox protobuf-compiler protobuf-c-compiler
`

**Comment by ffurrer** [comment]
Already in: https://github.com/ethz-asl/rotors_simulator/blob/master/README.md#installation-instructions---ubuntu-1604-with-ros-kinetic
