### ISSUE TITLE
Car and road model in the Wiki page

### ISSUE THREAD

**Issue by princeward** [ethz-asl/rotors_simulator#505]
In the wiki page, a picture of the following world with car and road is displayed.

I'm wondering is this world file included in the package somewhere?

If not, where can I find the relevant car/road model/plugin so that I can make them myself?

![RotorS simulation](https://github.com/ethz-asl/rotors_simulator/wiki/img/rotors_collaboration.png)

**Comment by shravank1996** [comment]
The road is from outdoor.world and the car is a generic car model available in gazebo
