### ISSUE TITLE
Error in catkin build

### ISSUE THREAD

**Issue by emmanuelovalle** [ethz-asl/rotors_simulator#520]
Hi, I have the next error during catkin build:

Could NOT find GeographicLib (missing: GeographicLib_LIBRARIES
  GeographicLib_INCLUDE_DIRS)

**Comment by zarmomin** [comment]
Installing GeographicLib per this https://geographiclib.sourceforge.io/html/install.html#autoconf fixed it for me

**Comment by nkhedekar** [comment]
Similar to https://github.com/mavlink/mavros/issues/884. It can be solved by running `sudo apt-get install libgeographic-dev ros-kinetic-geographic-msgs`

**Comment by ffurrer** [comment]
Closing this, as I guess the issue was solved and I added instructions to our wiki, thanks.
