### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by qingchunlizhi** [ethz-asl/rotors_simulator#523]
In file included from /home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:17:0:
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/include/rotors_hil_interface/hil_interface.h:105:3: error: ‘mavlink_hil_gps_t’ does not name a type
   mavlink_hil_gps_t hil_gps_msg_;
   ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/include/rotors_hil_interface/hil_interface.h:108:3: error: ‘mavlink_hil_sensor_t’ does not name a type
   mavlink_hil_sensor_t hil_sensor_msg_;
   ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/include/rotors_hil_interface/hil_interface.h:130:3: error: ‘mavlink_hil_state_quaternion_t’ does not name a type
   mavlink_hil_state_quaternion_t hil_state_qtrn_msg_;
   ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp: In member function ‘virtual std::vector<mavros_msgs::Mavlink_<std::allocator<void> > > rotors_hil::HilSensorLevelInterface::CollectData()’:
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:89:3: error: ‘mavlink_message_t’ was not declared in this scope
   mavlink_message_t mmsg;
   ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:89:3: note: suggested alternatives:
In file included from /home/duan/catkin_ws/devel/include/mavlink/v2.0/common/../message.hpp:15:0,
                 from /home/duan/catkin_ws/devel/include/mavlink/v2.0/common/common.hpp:16,
                 from /home/duan/catkin_ws/src/mavros/libmavconn/include/mavconn/mavlink_dialect.h:26,
                 from /home/duan/catkin_ws/src/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:18,
                 from /home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/include/rotors_hil_interface/hil_interface.h:23,
                 from /home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:17:
/home/duan/catkin_ws/devel/include/mavlink/v2.0/common/../mavlink_types.h:121:4: note:   ‘mavlink::mavlink_message_t’
 }) mavlink_message_t;
    ^
/home/duan/catkin_ws/devel/include/mavlink/v2.0/common/../mavlink_types.h:121:4: note:   ‘mavlink::mavlink_message_t’
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:105:5: error: ‘hil_gps_msg_’ was not declared in this scope
     hil_gps_msg_.time_usec = time_usec;
     ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:119:5: error: ‘mavlink_hil_gps_t’ was not declared in this scope
     mavlink_hil_gps_t* hil_gps_msg_ptr = &hil_gps_msg_;
     ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:119:24: error: ‘hil_gps_msg_ptr’ was not declared in this scope
     mavlink_hil_gps_t* hil_gps_msg_ptr = &hil_gps_msg_;
                        ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:120:39: error: ‘mmsg’ was not declared in this scope
     mavlink_msg_hil_gps_encode(1, 0, &mmsg, hil_gps_msg_ptr);
                                       ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:120:60: error: ‘mavlink_msg_hil_gps_encode’ was not declared in this scope
     mavlink_msg_hil_gps_encode(1, 0, &mmsg, hil_gps_msg_ptr);
                                                            ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:131:3: error: ‘hil_sensor_msg_’ was not declared in this scope
   hil_sensor_msg_.time_usec = time_usec;
   ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:147:3: error: ‘mavlink_hil_sensor_t’ was not declared in this scope
   mavlink_hil_sensor_t* hil_sensor_msg_ptr = &hil_sensor_msg_;
   ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:147:25: error: ‘hil_sensor_msg_ptr’ was not declared in this scope
   mavlink_hil_sensor_t* hil_sensor_msg_ptr = &hil_sensor_msg_;
                         ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:148:40: error: ‘mmsg’ was not declared in this scope
   mavlink_msg_hil_sensor_encode(1, 0, &mmsg, hil_sensor_msg_ptr);
                                        ^
/home/duan/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:148:64: error: ‘mavlink_msg_hil_sensor_encode’ was not declared in this scope
   mavlink_msg_hil_sensor_encode(1, 0, &mmsg, hil_sensor_msg_ptr);
                                                                ^
CMakeFiles/rotors_hil_interface.dir/build.make:62: recipe for target 'CMakeFiles/rotors_hil_interface.dir/src/hil_sensor_level_interface.cpp.o' failed
make[2]: *** [CMakeFiles/rotors_hil_interface.dir/src/hil_sensor_level_interface.cpp.o] Error 1
CMakeFiles/Makefile2:253: recipe for target 'CMakeFiles/rotors_hil_interface.dir/all' failed
make[1]: *** [CMakeFiles/rotors_hil_interface.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by user1409** [comment]
I do have the same Error. Not installing it does the trick, but if I wish to install it any suggestions @0Jiahao ?

**Comment by qingchunlizhi** [comment]
>https://github.com/ethz-asl/rotors_simulator/pull/522/files?fbclid=IwAR2SxViGule-u8S4A1kE0L6HCwW3cixtO7IgMBNTp9TILT62TGdXPlsxApw 
this solution works
