### ISSUE TITLE
problem after tuned control parameters

### ISSUE THREAD

**Issue by 0Jiahao** [ethz-asl/rotors_simulator#525]
Hi! I was trying to tune the yawrate control parameter (from 0.052 to 0.3) since I think the default yawrate controller is too slow. After I did this, I found when I gave a yawrate command, there is an obvious thrust decrease. Any idea what should I do to make the yawrate controller aggressive and at the same time the altitude can be roughly held?

**Comment by ffurrer** [comment]
which controller are you using?

**Comment by 0Jiahao** [comment]
@ffurrer hi, i am using the roll_pitch_yawrate controller and control it with a xbox joystick.
