### ISSUE TITLE
calculation of rotor inertia

### ISSUE THREAD

**Issue by Aminyazdanshenas** [ethz-asl/rotors_simulator#535]
Hey guys 
I've been reading urdf models of this project and there is something about rotor model used in iris.xacro file which I've been struggling with for a while. 
The problem is that just a cuboid moment of inertia (propeller is assumed a cuboid) is implemented in "rotor_inertia" property block and the motor itself is neglected.

`
    ixx="${1/12 * mass_rotor * (0.015 * 0.015 + 0.003 * 0.003) * rotor_velocity_slowdown_sim}"
`
`
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.003 * 0.003) * rotor_velocity_slowdown_sim}"
`
`
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.015 * 0.015) * rotor_velocity_slowdown_sim}"
`
`
    ixy="0.0" ixz="0.0"  iyz="0.0"
`

 As far as I know for some cases the amount of motor moment of inertia is comparable with propeller moment of inertia and a summation of these values must be used.

Best regards

**Comment by Jaeyoung-Lim** [comment]
You can include the motor inertia into the rotor inertia
