### ISSUE TITLE
Build failed with ros-melodic version.

### ISSUE THREAD

**Issue by EdXian** [ethz-asl/rotors_simulator#544]
Hi all,  
I try the same instruction as the ros-kinetic version. However, there were many error message as the follows:
![image](https://user-images.githubusercontent.com/28064159/51129328-269b8280-1865-11e9-934a-bb23ac402f7a.png)
![image](https://user-images.githubusercontent.com/28064159/51129339-2ef3bd80-1865-11e9-9d18-a1066aca36ef.png)
![image](https://user-images.githubusercontent.com/28064159/51129363-39ae5280-1865-11e9-9d9a-e132933b4a01.png)
![image](https://user-images.githubusercontent.com/28064159/51129369-40d56080-1865-11e9-8b28-418292fa13d7.png)
![image](https://user-images.githubusercontent.com/28064159/51129378-48950500-1865-11e9-8531-0c9d76b7c06d.png)

Can someone who compiles the package successfully with ros-melodic help me?
Thanks!!

**Comment by michaelpantic** [comment]
Should be fixed in new master.
