### ISSUE TITLE
What are the dimensions of the provided values ?

### ISSUE THREAD

**Issue by OmarRomdhani** [ethz-asl/rotors_simulator#578]
I was looking for a document that defines the dimensions of every parameter used in this pluging such as these tags :
`
<timeConstantUp>0.0125</timeConstantUp>
<timeConstantDown>0.0125</timeConstantDown>
<maxRotVelocity>10000</maxRotVelocity>
<motorConstant>8.54858e-05</motorConstant>
<momentConstant>0.016</momentConstant>
<rotorDragCoefficient>0.000806428</rotorDragCoefficient>
<rollingMomentCoefficient>0.000001</rollingMomentCoefficient>
<rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>`

and the dimension of the angular velocity values example :

` $ rostopic pub /firefly/command/motor_speed mav_msgs/Actuators '{angular_velocities: [100, 100, 100, 100, 100, 100]}' `

what are these 100 ? is it in RPM or rad/s or what ?
thanks in advance

**Comment by gsilano** [comment]
Please, take a look [here](https://link.springer.com/chapter/10.1007/978-3-030-20190-6_4). In this book chapter, you will find tables and other useful information of what you are looking for.
