### ISSUE TITLE
BUILD_OCTOMAP_PLUGIN failed

### ISSUE THREAD

**Issue by Wayne-xixi** [ethz-asl/rotors_simulator#603]
I'm using Gazebo 7 and ROS Kinetic ros-kinetic-octomap

I'm trying to use the octomap function as described in
https://github.com/ethz-asl/rotors_simulator/wiki/Generate-an-octomap-from-your-world

So I set BUILD_OCTOMAP_PLUGIN to TRUE
when I run catkin build, along with a bunch of warnings about things being deprecated, I get this error.
`Errors     << rotors_gazebo_plugins:make /home/dong/catkin_ws/logs/rotors_gazebo_plugins/build.make.007.log                                                                                                
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_gps_plugin.cpp: In member function ‘virtual void gazebo::GazeboGpsPlugin::Load(gazebo::sensors::SensorPtr, sdf::ElementPtr)’:
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_gps_plugin.cpp:45:60: warning: ‘std::__cxx11::string gazebo::sensors::Sensor::GetWorldName() const’ is deprecated [-Wdeprecated-declarations]
   world_ = physics::get_world(parent_sensor_->GetWorldName());
                                                            ^
In file included from /usr/include/gazebo-7/gazebo/sensors/AltimeterSensor.hh:25:0,
                 from /usr/include/gazebo-7/gazebo/sensors/sensors.hh:2,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/gazebo_gps_plugin.h:27,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_gps_plugin.cpp:19:
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:200:27: note: declared here
       public: std::string GetWorldName() const GAZEBO_DEPRECATED(7.0);
                           ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_gps_plugin.cpp: In member function ‘void gazebo::GazeboGpsPlugin::OnUpdate()’:
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_gps_plugin.cpp:177:57: warning: ‘gazebo::common::Time gazebo::sensors::Sensor::GetLastMeasurementTime()’ is deprecated [-Wdeprecated-declarations]
   current_time = parent_sensor_->GetLastMeasurementTime();
                                                         ^
In file included from /usr/include/gazebo-7/gazebo/sensors/AltimeterSensor.hh:25:0,
                 from /usr/include/gazebo-7/gazebo/sensors/sensors.hh:2,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/gazebo_gps_plugin.h:27,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_gps_plugin.cpp:19:
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:166:28: note: declared here
       public: common::Time GetLastMeasurementTime() GAZEBO_DEPRECATED(7.0);
                            ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp: In member function ‘virtual void gazebo::GazeboLidarPlugin::Load(gazebo::sensors::SensorPtr, sdf::ElementPtr)’:
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:75:69: warning: ‘std::__cxx11::string gazebo::sensors::Sensor::GetWorldName() const’ is deprecated [-Wdeprecated-declarations]
   this->world = physics::get_world(this->parentSensor->GetWorldName());
                                                                     ^
In file included from /usr/include/gazebo-7/gazebo/sensors/RaySensor.hh:26:0,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/external/gazebo_lidar_plugin.h:27,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:23:
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:200:27: note: declared here
       public: std::string GetWorldName() const GAZEBO_DEPRECATED(7.0);
                           ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:78:39: warning: ‘gazebo::physics::MultiRayShapePtr gazebo::sensors::RaySensor::GetLaserShape() const’ is deprecated [-Wdeprecated-declarations]
     this->parentSensor->GetLaserShape()->ConnectNewLaserScans(
                                       ^
In file included from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/external/gazebo_lidar_plugin.h:27:0,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:23:
/usr/include/gazebo-7/gazebo/sensors/RaySensor.hh:253:41: note: declared here
       public: physics::MultiRayShapePtr GetLaserShape()
                                         ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:89:52: warning: ‘std::__cxx11::string gazebo::sensors::Sensor::GetParentName() const’ is deprecated [-Wdeprecated-declarations]
   const string scopedName = _parent->GetParentName();
                                                    ^
In file included from /usr/include/gazebo-7/gazebo/sensors/RaySensor.hh:26:0,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/external/gazebo_lidar_plugin.h:27,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:23:
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:81:27: note: declared here
       public: std::string GetParentName() const
                           ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp: In member function ‘virtual void gazebo::GazeboLidarPlugin::OnNewLaserScans()’:
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:101:60: warning: ‘double gazebo::sensors::RaySensor::GetRangeMin() const’ is deprecated [-Wdeprecated-declarations]
   lidar_message.set_min_distance(parentSensor->GetRangeMin());
                                                            ^
In file included from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/external/gazebo_lidar_plugin.h:27:0,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:23:
/usr/include/gazebo-7/gazebo/sensors/RaySensor.hh:94:22: note: declared here
       public: double GetRangeMin() const GAZEBO_DEPRECATED(7.0);
                      ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:102:60: warning: ‘double gazebo::sensors::RaySensor::GetRangeMax() const’ is deprecated [-Wdeprecated-declarations]
   lidar_message.set_max_distance(parentSensor->GetRangeMax());
                                                            ^
In file included from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/external/gazebo_lidar_plugin.h:27:0,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:23:
/usr/include/gazebo-7/gazebo/sensors/RaySensor.hh:103:22: note: declared here
       public: double GetRangeMax() const GAZEBO_DEPRECATED(7.0);
                      ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:103:62: warning: ‘double gazebo::sensors::RaySensor::GetRange(unsigned int)’ is deprecated [-Wdeprecated-declarations]
   lidar_message.set_current_distance(parentSensor->GetRange(0));
                                                              ^
In file included from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/external/gazebo_lidar_plugin.h:27:0,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_lidar_plugin.cpp:23:
/usr/include/gazebo-7/gazebo/sensors/RaySensor.hh:181:22: note: declared here
       public: double GetRange(unsigned int _index) GAZEBO_DEPRECATED(7.0);
                      ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp: In member function ‘bool gazebo::OctomapFromGazeboWorld::ServiceCallback(rotors_comm::Octomap::Request&, rotors_comm::Octomap::Response&)’:
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:91:42: error: no matching function for call to ‘gazebo::common::SphericalCoordinates::SphericalFromLocal(gazebo::math::Vector3&)’
       SphericalFromLocal(origin_cartesian);
                                          ^
In file included from /usr/include/gazebo-7/gazebo/common/common.hh:40:0,
                 from /usr/include/gazebo-7/gazebo/gazebo_core.hh:19,
                 from /usr/include/gazebo-7/gazebo/gazebo.hh:20,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/common.h:26,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/gazebo_octomap_plugin.h:28,
                 from /home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:21:
/usr/include/gazebo-7/gazebo/common/SphericalCoordinates.hh:96:40: note: candidate: ignition::math::Vector3d gazebo::common::SphericalCoordinates::SphericalFromLocal(const Vector3d&) const
       public: ignition::math::Vector3d SphericalFromLocal(
                                        ^
/usr/include/gazebo-7/gazebo/common/SphericalCoordinates.hh:96:40: note:   no known conversion for argument 1 from ‘gazebo::math::Vector3’ to ‘const Vector3d& {aka const ignition::math::Vector3<double>&}’
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp: In member function ‘void gazebo::OctomapFromGazeboWorld::FloodFill(const gazebo::math::Vector3&, const gazebo::math::Vector3&, const gazebo::math::Vector3&, double)’:
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:107:8: error: ‘std::stackoctomath’ has not been declared
   std::stackoctomath::Vector3 > to_check;
        ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:107:33: error: ‘to_check’ was not declared in this scope
   std::stackoctomath::Vector3 > to_check;
                                 ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:108:12: error: ‘pushoctomath’ has not been declared
   to_check.pushoctomath::Vector3 (seed_point.x, seed_point.y, seed_point.z));
            ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:122:16: error: ‘pushoctomath’ has not been declared
       to_check.pushoctomath::Vector3 (p.x() + leaf_size, p.y(), p.z()));
                ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:123:16: error: ‘pushoctomath’ has not been declared
       to_check.pushoctomath::Vector3 (p.x() - leaf_size, p.y(), p.z()));
                ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:124:16: error: ‘pushoctomath’ has not been declared
       to_check.pushoctomath::Vector3 (p.x(), p.y() + leaf_size, p.z()));
                ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:125:16: error: ‘pushoctomath’ has not been declared
       to_check.pushoctomath::Vector3 (p.x(), p.y() - leaf_size, p.z()));
                ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:126:16: error: ‘pushoctomath’ has not been declared
       to_check.pushoctomath::Vector3 (p.x(), p.y(), p.z() + leaf_size));
                ^
/home/dong/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_octomap_plugin.cpp:127:16: error: ‘pushoctomath’ has not been declared
       to_check.pushoctomath::Vector3 (p.x(), p.y(), p.z() - leaf_size));
                ^
`
Anyone can help me? Thank you in advance!

**Comment by Jaeyoung-Lim** [comment]
Seems like this has been fixed in https://github.com/ethz-asl/rotors_simulator/pull/645
