### ISSUE TITLE
/opt/ros/kinetic/lib/robot_state_publisher/robot_state_publisher /joint_states

### ISSUE THREAD

**Issue by hadhemi123** [ethz-asl/rotors_simulator#608]
can anyone explain this error for me ?

ERROR] [1585605588.676394658]: Error reading end tag.
[robot_state_publisher-3] processhas died [pid 16071, exit code 255, cmd /opt/ros/kinetic/lib/robot_state_publisher/robot_state_publisher /joint_states:=/gurdy/joint_states __name:=robot_state_publisher__log:=/home/user/.ros/log/55a840c2-72c3-11ea-9a22-02e9201d1506/robot_state_publisher-3.log].
log file: /home/user/.ros/log/55a840c2-72c3-11ea-9a22-02e9201d1506/robot_state_publisher-3*.log

**Comment by Jaeyoung-Lim** [comment]
I am closing this issue, since ROS kinetic will no longer be supported.
