### ISSUE TITLE
catkin build faleid with OpenCV4

### ISSUE THREAD

**Issue by arnaldojr** [ethz-asl/rotors_simulator#613]
hello,
I'm trying to catkin build with ROS Melodic and OpenCV4.1.1 ubuntu18. Following the instruction on [BebopS](https://github.com/gsilano/BebopS) repository. 

 Below the result:
![catkin1](https://user-images.githubusercontent.com/6247791/79783788-92e21d00-8317-11ea-969b-d31178746897.png)

I find one solution:

I replaced `CV_LOAD_IMAGE_GRAYSCALE` to` cv::IMREAD_GRAYSCALE` on `~/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_odometry_plugin.cpp`.

the result catkin build:
![Screenshot from 2020-04-20 14-22-26](https://user-images.githubusercontent.com/6247791/79783907-c91f9c80-8317-11ea-8dda-b1599f0bfc8e.png)

I think there will be no problems with other opencv versions.

**Comment by d3dx13** [comment]
edit file ~/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/external/gazebo_geotagged_images_plugin.cpp
replace:
"#include <cv.h>" -> "//#include <cv.h>" 
"#include <highgui.h>" -> "#include "opencv2/highgui/highgui.hpp""
"cvtColor(frame, frameBGR, CV_RGB2BGR);" -> "cvtColor(frame, frameBGR, COLOR_RGB2BGR);"

edit file ~/catkin_ws/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_odometry_plugin.cpp
replace:
"CV_LOAD_IMAGE_GRAYSCALE" -> "cv::IMREAD_GRAYSCALE"

**Comment by rikba** [comment]
Fixed here already: https://github.com/ethz-asl/rotors_simulator/commit/e05692abd9753957dff542653afefa05c341e0ce
