### ISSUE TITLE
The frame_rate of camera is too low to work with apriltag_ros

### ISSUE THREAD

**Issue by yorklyb** [ethz-asl/rotors_simulator#625]
Have been using rotors with apriltags_ros. 
video link:
https://www.youtube.com/watch?v=6Rfe5IMUqqY
But the frequency of the topic of /tag_detections is only 2.2 Hz. To make the apriltags_ros works well, I need to make sure the frequency of this topic is over 10 Hz.
And I found that the frequency of /image_raw was only 2.3 Hz. I tried to modify the <update_rate>in "component_snippets.xacro". However, even if the default value of frame_rate was 30.0, the /image_raw never reached 3 Hz. But if I changed it to 0.5 or 1.0, I could see the frequency decreased.

I don't think it is a problem with CPU. Because when I was running the turtlebot simulation, the frequency of /image_raw was over 11 Hz.

What should I do to improve this?

**Comment by MajdWardeh** [comment]
Hello yorklyb,

Were you able to figure this out?

Regards,
