### ISSUE TITLE
Fixed Wing Controllers

### ISSUE THREAD

**Issue by rohanblueboybaijal** [ethz-asl/rotors_simulator#631]
Are there any plans for PID and MPC controllers being implemented for Fixed Wing Aircraft in rotors_simulator?

I also found some repositories which had some plans of integration into rotorS like this one.
https://github.com/PX4/sitl_gazebo

But I'm not being able to get a clear picture about controllers.

**Comment by Jaeyoung-Lim** [comment]
@rohanblueboybaijal https://github.com/PX4/sitl_gazebo is a submodule of the https://github.com/PX4/Firmware

**Comment by rohanblueboybaijal** [comment]
@Jaeyoung-Lim I'm very sorry about the confusion about that.

Just trying to ask about any plans for fixed wing/VTOL MPC implementations in RotorS
