### ISSUE TITLE
rotos_gazebo_plugins cmake error

### ISSUE THREAD

**Issue by w407022008** [ethz-asl/rotors_simulator#632]
Hello, 
when i `catkin build`, an error apeares that 

> In file included from /home/sique/catkin_ws/build/rotors_gazebo_plugins/Actuators.pb.cc:4:0:
/home/sique/catkin_ws/build/rotors_gazebo_plugins/Actuators.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mav_msgs.dir/Actuators.pb.cc.o] Error 1

What is that? and how could we handle it?
Ze

**Comment by Jaeyoung-Lim** [comment]
Solved in discussion of https://github.com/ethz-asl/rotors_simulator/issues/592
