### ISSUE TITLE
Interfacing MavROS SITL from Ardupilot/PX4?

### ISSUE THREAD

**Issue by evandanrao** [ethz-asl/rotors_simulator#649]
(Beginner, Please bear) Hey I see that RotorS provides quite good Xacro and Wind Plugin options but I wish to connect an SITL from Ardupilot/ PX4 as a backend for the simulation on RotorS Simulator. Where do I open up a UDP Port in RotorS? I only see Mavlink Interface Enable, But can it take in a UDP connection ?

**Comment by Jaeyoung-Lim** [comment]
@evandanrao If you are using PX4, everything is already integrated into px4 in https://github.com/PX4/PX4-SITL_gazebo which has started from rotorS.
