### ISSUE TITLE
catkin build error when installing RotorS

### ISSUE THREAD

**Issue by wendy-ziwen-meng** [ethz-asl/rotors_simulator#668]
When installing RotorS following the instructions for 16.04 kinetic on https://github.com/ttdm/rotors_simulator,
I faced the error when typed in the 'catkin build', the errors are shown below:
![1](https://user-images.githubusercontent.com/84087309/120058711-82a28280-c07f-11eb-8e30-22e9b043768e.png)
![2](https://user-images.githubusercontent.com/84087309/120058715-86360980-c07f-11eb-80e2-1966baa8fdc1.png)
![3](https://user-images.githubusercontent.com/84087309/120058717-88986380-c07f-11eb-8546-a406e8aab320.png)
![4](https://user-images.githubusercontent.com/84087309/120058719-8b935400-c07f-11eb-80d9-348a654423dd.png)
What should I do to fix this?

**Comment by Jaeyoung-Lim** [comment]
You can try installing the missing python dependencies.

However, ROS Kinetic is End of Life since April, therefore wont be maintained further on

**Comment by tturkmen** [comment]
I use ros melodic. Thanks. I will format computer than try again.

**Comment by Jaeyoung-Lim** [comment]
Closing as stale
