### ISSUE TITLE
Build in Noetic

### ISSUE THREAD

**Issue by a-tab-a** [ethz-asl/rotors_simulator#673]
Hello,

I am trying to build this Ubuntu 20.04 ROS Noetic but could not do so and getting following error.  It is related to ignition-common3-graphics, I install this package along with gazebo and gazebo does start up. It shows there is a version mismatch, how to work around this? Thanks
![1](https://user-images.githubusercontent.com/25964596/125875502-ccc49e57-2305-4690-9aeb-2ae636bf5056.PNG)
![2](https://user-images.githubusercontent.com/25964596/125875503-8a63ec67-45af-4cab-874f-d879eab8f766.PNG)

**Comment by a-tab-a** [comment]
Never mind just upgrading works! Closing since got it work.

**Comment by zhengleily** [comment]
I encountered the same issue” . How do you fix this error?

**Comment by zhengleily** [comment]
I encountered the same issue!
How do you fix this error exactly?
