### ISSUE TITLE
How to use the .rosinstall files to install the dependencies?

### ISSUE THREAD

**Issue by SchandraS** [ethz-asl/rotors_simulator#680]
question: I'm confused on how to use the .rosinstall files to install the dependencies. i'm not exactly sure on how to use them.

**Comment by Jaeyoung-Lim** [comment]
@SchandraS I believe your question is not directly related to this repository, and more of a question related to using ROS in general

You can look up the tutorial in documentations like https://docs.ros.org/en/independent/api/rosinstall/html/

**Comment by tkazik** [comment]
@SchandraS You can for instance use [vcstool](https://github.com/dirk-thomas/vcstool) and invoke the following command in the `src` directory of your workspace:

```shell
vcs import < rotors_simulator/rotors_minimal.rosinstall
```

This will fetch all the packages required to build rotors. 

Note1: In the case of [rotors_minimal.rosinstall](https://github.com/ethz-asl/rotors_simulator/blob/master/rotors_minimal.rosinstall) it is only one package, namely [mav_comm](https://github.com/ethz-asl/mav_comm)
Note2: The [dependencies.rosinstall](https://github.com/ethz-asl/rotors_simulator/blob/master/dependencies.rosinstall) seems to pull in some outdated/broken packages (at least for Ubuntu20.04)...we might need to fix these.
